/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.ayudantia.ejcat2.ej2.views;

import javax.swing.JTabbedPane;
import poo.ayudantia.ejcat2.ej2.models.Usuario;

/**
 *
 * @author sebaignacioo
 */
public class AppFrame extends javax.swing.JFrame {

    private Usuario usuario;

    /**
     * Creates new form AppFrame
     */
    public AppFrame(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        lblUsuario.setText(lblUsuario.getText() + usuario.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        panelMain = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));

        lblUsuario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblUsuario.setText("Usuario: ");

        panelMain.setMaximumSize(new java.awt.Dimension(780, 440));
        panelMain.setMinimumSize(new java.awt.Dimension(780, 440));
        panelMain.setPreferredSize(new java.awt.Dimension(780, 440));
        panelMain.setSize(new java.awt.Dimension(780, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblUsuario)
                .addGap(18, 18, 18)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTabbedPane panelMain;
    // End of variables declaration//GEN-END:variables

    public JTabbedPane getPanelMain() {
        return panelMain;
    }

    
    
}
