/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poo.ayudantia.ejcat2.ej2.views.panels;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTable;
import poo.ayudantia.ejcat2.ej2.models.Producto;

/**
 *
 * @author sebaignacioo
 */
public class ComprasPanel extends javax.swing.JPanel {

    /**
     * Creates new form ComprasPanel
     */
    public ComprasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        tableCompras = new javax.swing.JTable();
        lblAgregarCompra = new javax.swing.JLabel();
        cbInsumos = new javax.swing.JComboBox<>();
        txtCantidadAComprar = new javax.swing.JSpinner();
        btnAgregarCompra = new javax.swing.JButton();
        lblSeleccionarProducto = new javax.swing.JLabel();
        lblSeleccionarProducto1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(780, 440));
        setMinimumSize(new java.awt.Dimension(780, 440));
        setPreferredSize(new java.awt.Dimension(780, 440));
        setSize(new java.awt.Dimension(780, 440));

        tableCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre producto", "Cantidad", "Usuario", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCompras.setMaximumSize(new java.awt.Dimension(780, 300));
        tableCompras.setMinimumSize(new java.awt.Dimension(780, 300));
        tableCompras.setPreferredSize(new java.awt.Dimension(780, 300));
        tableCompras.setSize(new java.awt.Dimension(780, 300));
        scrollPanel.setViewportView(tableCompras);

        lblAgregarCompra.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblAgregarCompra.setText("Agregar compra");

        txtCantidadAComprar.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnAgregarCompra.setText("Agregar compra");

        lblSeleccionarProducto.setText("Seleccionar producto");

        lblSeleccionarProducto1.setText("Cantidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregarCompra)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeleccionarProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeleccionarProducto1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCantidadAComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(scrollPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAgregarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccionarProducto)
                    .addComponent(lblSeleccionarProducto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadAComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCompra))
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCompra;
    private javax.swing.JComboBox<Producto> cbInsumos;
    private javax.swing.JLabel lblAgregarCompra;
    private javax.swing.JLabel lblSeleccionarProducto;
    private javax.swing.JLabel lblSeleccionarProducto1;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JTable tableCompras;
    private javax.swing.JSpinner txtCantidadAComprar;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregarCompra() {
        return btnAgregarCompra;
    }

    public JComboBox<Producto> getCbInsumos() {
        return cbInsumos;
    }

    public JTable getTableCompras() {
        return tableCompras;
    }

    public JSpinner getTxtCantidadAComprar() {
        return txtCantidadAComprar;
    }

}
