/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poo.ayudantia.ejcat2.ej2.views.panels;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTable;
import poo.ayudantia.ejcat2.ej2.models.Producto;

/**
 *
 * @author sebaignacioo
 */
public class VentasPanel extends javax.swing.JPanel {

    /**
     * Creates new form ComprasPanel
     */
    public VentasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        tableVentas = new javax.swing.JTable();
        lblAgregarVenta = new javax.swing.JLabel();
        cbProdVenta = new javax.swing.JComboBox<>();
        txtCantidadAVender = new javax.swing.JSpinner();
        btnAgregarVenta = new javax.swing.JButton();
        lblSeleccionarProducto = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(780, 440));
        setMinimumSize(new java.awt.Dimension(780, 440));
        setPreferredSize(new java.awt.Dimension(780, 440));
        setSize(new java.awt.Dimension(780, 440));

        tableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre producto", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVentas.setMaximumSize(new java.awt.Dimension(780, 300));
        tableVentas.setMinimumSize(new java.awt.Dimension(780, 300));
        tableVentas.setPreferredSize(new java.awt.Dimension(780, 300));
        tableVentas.setSize(new java.awt.Dimension(780, 300));
        scrollPanel.setViewportView(tableVentas);

        lblAgregarVenta.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblAgregarVenta.setText("Agregar venta");

        txtCantidadAVender.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnAgregarVenta.setText("Agregar venta");

        lblSeleccionarProducto.setText("Seleccionar producto");

        lblCantidad.setText("Cantidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregarVenta)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeleccionarProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidad)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCantidadAVender, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(scrollPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAgregarVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccionarProducto)
                    .addComponent(lblCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadAVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarVenta))
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarVenta;
    private javax.swing.JComboBox<Producto> cbProdVenta;
    private javax.swing.JLabel lblAgregarVenta;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblSeleccionarProducto;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JTable tableVentas;
    private javax.swing.JSpinner txtCantidadAVender;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregarVenta() {
        return btnAgregarVenta;
    }

    public JComboBox<Producto> getCbProdVenta() {
        return cbProdVenta;
    }

    public JTable getTableVentas() {
        return tableVentas;
    }

    public JSpinner getTxtCantidadAVender() {
        return txtCantidadAVender;
    }

    

}
